version: '3.8'

networks:
  app-network:

volumes:
  app-data:

services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:

  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: backend
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      app-network:


  dbvs:
    image:
      "mariadb:focal"
    environment:
      MARIADB_USER: "root"
      MARIADB_PASSWORD: "root"
      MARIADB_ROOT_PASSWORD: "root"
    user: "root"
    ports:
      - "3306:3306/tcp"
    volumes:
      - "./db/data/mariadb:/var/lib/mysql"
    networks:
      app-network:

  phpmyadmin:
    image:
      "phpmyadmin:latest"
    environment:
      PMA_USER: "root"
      PMA_PASSWORD: "root"
    ports:
      - "8080:80/tcp"
    links:
      - "dbvs:db"
    networks:
      app-network:
